#!/usr/bin/env python3
"""Build callback receiver OpenAPI specs from the original NF YAMLs.

The 4 producer-side YAMLs in this repo (Nncof/Nupf/Nnef/Nsmf) declare their
notification callbacks with OpenAPI's inline `callbacks:` keyword. OpenAPI
Generator (python-fastapi) does *not* generate server stubs from that section,
so consumer-side NFs (e.g. PCF/RICF that receive Nncof notifications, NCOF
that receives Nupf/Nnef/Nsmf notifications) cannot get a ready-to-implement
FastAPI server from the original specs.

This script extracts each notification endpoint into a standalone OpenAPI
document under `callbacks/`, suitable for code generation.

Two schema simplifications are applied during extraction (the original YAMLs
are NOT modified):

  1. `oneOf` constraints are dropped at every level (validation deferred to
     business logic). OpenAPI Generator's python-fastapi template otherwise
     produces an empty model class when properties and oneOf coexist.

  2. The 3GPP "forward-compatible enum" pattern,

         anyOf:
           - type: string
             enum: [VAL_A, VAL_B, ...]
           - type: string

     is flattened to plain `type: string`. The python-fastapi generator
     models the `anyOf` as a wrapper class and rejects plain string inputs.

All cross-file `$ref`s are inlined into a single self-contained document,
with simplification applied transitively to every reachable schema and to
every shared response (ProblemDetails, RedirectResponse, ...).

Usage
-----
    python tools/build_callbacks.py            # rebuild every callback YAML
    python tools/build_callbacks.py nncof      # rebuild only Nncof
    python tools/build_callbacks.py nncof nupf # rebuild a subset

Run from the repository root. Requires PyYAML (`pip install pyyaml`).

Outputs (overwrites in place):
    callbacks/Nncof_EventsSubscriptionNotification_Callback_PoC_ETRI_DoDo1.yaml
    callbacks/...  (Nupf/Nnef/Nsmf -- not yet configured)

Each generated file carries a `# !!! GENERATED FILE - DO NOT EDIT MANUALLY !!!`
header so reviewers know the file is reproducible.
"""
from __future__ import annotations

import argparse
import copy
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

# ---------------------------------------------------------------------------
# Layout
# ---------------------------------------------------------------------------

REPO_ROOT = Path(__file__).resolve().parent.parent
CALLBACKS_DIR = REPO_ROOT / "callbacks"

# Domain YAMLs that are searched when resolving cross-file $refs.
DOMAIN_YAMLS = (
    "Nncof_EventsSubscription_PoC_ETRI_DoDo1.yaml",
    "TS29508_Nsmf_EventExposure_PoC_ETRI_DoDo1.yaml",
    "TS29564_Nupf_EventExposure_PoC_ETRI_DoDo1.yaml",
    "TS29591_Nnef_EventExposure_PoC_ETRI_DoDo1.yaml",
    "TS29571_CommonData_PoC_ETRI_DoDo1.yaml",
    "TS29122_CommonData_PoC_ETRI_DoDo1.yaml",
    "TS26510_CommonData_PoC_ETRI_DoDo1.yaml",
    "TS26512_CommonData_PoC_ETRI_DoDo1.yaml",
    "SupplementaryData_PoC_ETRI_DoDo1.yaml",
)

# Standard error response codes referenced by every callback endpoint.
ERROR_RESPONSE_CODES = (
    "307", "308",
    "400", "401", "403", "404", "411", "413", "415", "429",
    "500", "502", "503",
    "default",
)

# Where the standard responses (referenced by ERROR_RESPONSE_CODES) live.
RESPONSES_FILE = "TS29571_CommonData_PoC_ETRI_DoDo1.yaml"

GENERATED_HEADER = (
    "# !!! GENERATED FILE - DO NOT EDIT MANUALLY !!!\n"
    "# Generated by tools/build_callbacks.py from the original NF YAMLs.\n"
    "# Edit the original spec instead, then re-run:\n"
    "#     python tools/build_callbacks.py\n"
)


# ---------------------------------------------------------------------------
# Per-callback configuration
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class CallbackSpec:
    """Configuration for a single callback receiver YAML."""

    key: str                        # CLI selector, e.g. "nncof"
    title: str
    description: str
    output_filename: str            # under callbacks/
    root_file: str                  # source NF YAML for the notification schema
    root_schema: str                # name of the root notification schema
    callback_path: str              # path under the consumer's base URL
    operation_id: str
    tag: str
    auth_scope: str                 # OAuth2 scope name
    auth_scope_description: str
    request_is_array: bool          # whether the request body is an array
    request_min_items: int = 1


CALLBACKS: dict[str, CallbackSpec] = {
    "nncof": CallbackSpec(
        key="nncof",
        title="Nncof_EventsSubscriptionNotification (Callback Receiver)",
        description=(
            "Callback receiver specification for the Nncof_EventsSubscription service.\n\n"
            "This spec is consumed by NF service consumers (e.g., PCF, RICF) that subscribe\n"
            "to NCOF events. Such consumers must implement an HTTP server that exposes the\n"
            "endpoint defined here so that NCOF can deliver Subscription Notifications to it.\n\n"
            "It is intentionally extracted from `Nncof_EventsSubscription_PoC_ETRI_DoDo1.yaml`\n"
            "because OpenAPI Generator does not generate server stubs for the `callbacks:`\n"
            "section of an OpenAPI document. Generating from this standalone spec yields a\n"
            "ready-to-implement FastAPI server stub on the consumer side.\n\n"
            "Schema simplifications applied for code-generator compatibility (the original\n"
            "Nncof_EventsSubscription_PoC_ETRI_DoDo1.yaml is unchanged):\n"
            "  - `oneOf` constraints are dropped (validation deferred to business logic).\n"
            "  - 3GPP forward-compatible enum pattern (`anyOf: [enum-string, free-string]`)\n"
            "    is flattened to plain `type: string`.\n"
            "  - All cross-file `$ref`s are inlined into this single document.\n\n"
            "NCOF Event Exposure Service for 6G-I2P PoC Scenario.\n"
        ),
        output_filename="Nncof_EventsSubscriptionNotification_Callback_PoC_ETRI_DoDo1.yaml",
        root_file="Nncof_EventsSubscription_PoC_ETRI_DoDo1.yaml",
        root_schema="NncofEventsSubscriptionNotification",
        callback_path="/notifications",
        operation_id="ReceiveNCOFEventsSubscriptionNotification",
        tag="NCOF Events Subscription Notification (Callback Receiver)",
        auth_scope="nncof-eventssubscription",
        auth_scope_description="Access to the Nncof_EventsSubscription API",
        request_is_array=True,
        request_min_items=1,
    ),
    # Future:
    #   "nupf": CallbackSpec(...),
    #   "nnef": CallbackSpec(...),
    #   "nsmf": CallbackSpec(...),
}


# ---------------------------------------------------------------------------
# YAML loading
# ---------------------------------------------------------------------------


@dataclass
class Workspace:
    docs: dict[str, dict] = field(default_factory=dict)

    def load(self) -> None:
        for name in DOMAIN_YAMLS:
            with (REPO_ROOT / name).open() as f:
                self.docs[name] = yaml.safe_load(f)

    def schema(self, file: str, name: str) -> dict:
        return self.docs[file]["components"]["schemas"][name]

    def response(self, file: str, name: str) -> dict:
        return self.docs[file]["components"]["responses"][name]


# ---------------------------------------------------------------------------
# Schema simplification
# ---------------------------------------------------------------------------


def _is_forward_compat_enum(node: dict) -> bool:
    """Detect 3GPP forward-compatible enum pattern."""
    items = node.get("anyOf")
    if not isinstance(items, list) or len(items) != 2:
        return False
    a, b = items
    if not (isinstance(a, dict) and isinstance(b, dict)):
        return False
    return (
        a.get("type") == "string"
        and isinstance(a.get("enum"), list)
        and b.get("type") == "string"
        and "enum" not in b
    )


def simplify(node: Any) -> Any:
    """Recursively simplify a schema for code-generator compatibility.

    See module docstring for which transformations are applied and why.
    """
    if isinstance(node, dict):
        if "oneOf" in node:
            node = {k: v for k, v in node.items() if k != "oneOf"}
        if _is_forward_compat_enum(node):
            simplified: dict = {"type": "string"}
            if "description" in node:
                simplified["description"] = node["description"]
            return simplified
        return {k: simplify(v) for k, v in node.items()}
    if isinstance(node, list):
        return [simplify(x) for x in node]
    return node


# ---------------------------------------------------------------------------
# $ref resolution and inlining
# ---------------------------------------------------------------------------


def _parse_ref(ref: str, current_file: str) -> tuple[str, str]:
    """Return (file, schema_name). External file refs use the file in the prefix;
    fragment-only refs (`#/...`) resolve against ``current_file``."""
    prefix, _, fragment = ref.partition("#")
    file = prefix or current_file
    name = fragment.rsplit("/", 1)[-1]
    return file, name


def _rewrite_local(node: Any, current_file: str, found: set[tuple[str, str]]) -> None:
    """Walk ``node`` in place: rewrite every $ref to '#/components/schemas/<Name>'
    and record (source_file, schema_name) of each referenced schema."""
    if isinstance(node, dict):
        if "$ref" in node and isinstance(node["$ref"], str):
            file, name = _parse_ref(node["$ref"], current_file)
            node["$ref"] = f"#/components/schemas/{name}"
            found.add((file, name))
            return
        for v in node.values():
            _rewrite_local(v, current_file, found)
    elif isinstance(node, list):
        for x in node:
            _rewrite_local(x, current_file, found)


def collect_schema_tree(
    workspace: Workspace,
    root_file: str,
    root_name: str,
) -> dict[str, dict]:
    """Walk the schema dependency tree from ``root_name`` and return a dict
    of ``{schema_name: simplified_schema}``. All $refs in the returned schemas
    are local (`#/components/schemas/<Name>`)."""
    out: dict[str, dict] = {}
    queue: list[tuple[str, str]] = [(root_file, root_name)]
    while queue:
        file, name = queue.pop(0)
        if name in out:
            continue
        try:
            raw = workspace.schema(file, name)
        except KeyError:
            raise SystemExit(f"schema {name!r} not found in {file}")
        schema = simplify(copy.deepcopy(raw))
        new_refs: set[tuple[str, str]] = set()
        _rewrite_local(schema, file, new_refs)
        out[name] = schema
        queue.extend(new_refs)
    return out


def collect_response_block(
    workspace: Workspace,
    schemas: dict[str, dict],
) -> dict[str, dict]:
    """Build the standard error responses block, inlining every cross-file
    schema $ref into ``schemas`` so the resulting YAML is self-contained."""
    responses: dict[str, dict] = {}
    queue: list[tuple[str, str]] = []
    for code in ERROR_RESPONSE_CODES:
        raw = workspace.response(RESPONSES_FILE, code)
        node = simplify(copy.deepcopy(raw))
        new_refs: set[tuple[str, str]] = set()
        _rewrite_local(node, RESPONSES_FILE, new_refs)
        responses[code] = node
        queue.extend(new_refs)
    while queue:
        file, name = queue.pop(0)
        if name in schemas:
            continue
        try:
            raw = workspace.schema(file, name)
        except KeyError:
            raise SystemExit(f"response-referenced schema {name!r} not found in {file}")
        schema = simplify(copy.deepcopy(raw))
        nested: set[tuple[str, str]] = set()
        _rewrite_local(schema, file, nested)
        schemas[name] = schema
        queue.extend(nested)
    return responses


# ---------------------------------------------------------------------------
# OpenAPI document assembly
# ---------------------------------------------------------------------------


def build_document(spec: CallbackSpec, workspace: Workspace) -> dict:
    schemas = collect_schema_tree(workspace, spec.root_file, spec.root_schema)
    responses = collect_response_block(workspace, schemas)
    schemas_sorted = {k: schemas[k] for k in sorted(schemas)}

    if spec.request_is_array:
        request_schema = {
            "type": "array",
            "items": {"$ref": f"#/components/schemas/{spec.root_schema}"},
            "minItems": spec.request_min_items,
        }
    else:
        request_schema = {"$ref": f"#/components/schemas/{spec.root_schema}"}

    paths_block = {
        spec.callback_path: {
            "post": {
                "summary": f"Receive a notification ({spec.root_schema})",
                "description": (
                    "Endpoint that the NF service consumer implements to receive "
                    "Notifications generated by the producer NF. The producer calls this "
                    "endpoint using the URI registered as the notification URI at "
                    "subscription creation time."
                ),
                "operationId": spec.operation_id,
                "tags": [spec.tag],
                "requestBody": {
                    "required": True,
                    "content": {"application/json": {"schema": request_schema}},
                },
                "responses": {
                    "204": {"description": "The receipt of the Notification is acknowledged."},
                    **responses,
                },
            }
        }
    }

    return {
        "openapi": "3.0.0",
        "info": {
            "version": "0.1.0",
            "title": spec.title,
            "description": spec.description,
        },
        "security": [
            {},
            {"oAuth2ClientCredentials": [spec.auth_scope]},
        ],
        "servers": [
            {
                "description": "SwaggerHub API Auto Mocking",
                "url": (
                    "https://virtserver.swaggerhub.com/ETRI_INRS_TEAM/"
                    f"{Path(spec.output_filename).stem}/0.1.0"
                ),
            },
            {
                "url": "{notifApiRoot}",
                "variables": {
                    "notifApiRoot": {
                        "default": "https://example.com",
                        "description": (
                            "The base URL of the consumer NF that receives notifications "
                            "from the producer. The full callback URL registered during "
                            f"subscription must be `{{notifApiRoot}}` + `{spec.callback_path}`."
                        ),
                    }
                },
            },
        ],
        "paths": paths_block,
        "components": {
            "securitySchemes": {
                "oAuth2ClientCredentials": {
                    "type": "oauth2",
                    "flows": {
                        "clientCredentials": {
                            "tokenUrl": "{nrfApiRoot}/oauth2/token",
                            "scopes": {spec.auth_scope: spec.auth_scope_description},
                        }
                    },
                }
            },
            "schemas": schemas_sorted,
        },
    }


# ---------------------------------------------------------------------------
# YAML emission
# ---------------------------------------------------------------------------


class _BlockStringDumper(yaml.SafeDumper):
    """yaml.SafeDumper that emits multi-line strings as block scalars (`|`),
    which is far easier to read for OpenAPI descriptions."""


def _str_presenter(dumper: yaml.SafeDumper, data: str):
    if "\n" in data:
        return dumper.represent_scalar("tag:yaml.org,2002:str", data, style="|")
    return dumper.represent_scalar("tag:yaml.org,2002:str", data)


_BlockStringDumper.add_representer(str, _str_presenter)


def write_callback_yaml(spec: CallbackSpec, doc: dict) -> Path:
    out = CALLBACKS_DIR / spec.output_filename
    out.parent.mkdir(parents=True, exist_ok=True)
    body = yaml.dump(
        doc,
        Dumper=_BlockStringDumper,
        sort_keys=False,
        allow_unicode=True,
        width=120,
    )
    out.write_text(GENERATED_HEADER + body)
    return out


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n", 1)[0])
    parser.add_argument(
        "names",
        nargs="*",
        choices=sorted(CALLBACKS) + [[]],  # type: ignore[list-item]
        help="Subset of callback specs to (re)build. Default: all.",
    )
    args = parser.parse_args(argv)

    selected = args.names or sorted(CALLBACKS)
    workspace = Workspace()
    workspace.load()

    for key in selected:
        spec = CALLBACKS[key]
        doc = build_document(spec, workspace)
        out = write_callback_yaml(spec, doc)
        size = out.stat().st_size
        n_schemas = len(doc["components"]["schemas"])
        print(f"  {key:6s}  -> {out.relative_to(REPO_ROOT)}  ({n_schemas} schemas, {size:,} bytes)")

    return 0


if __name__ == "__main__":
    sys.exit(main())
