#!/usr/bin/env python3
"""Build generator-friendly simplified OpenAPI specs (producer-side).

This script creates a parallel spec set under `simplified/` from the original
YAML files in this repository. The original specs remain unchanged and continue
to serve as the source of truth for standard conformance.

Why this exists
---------------
openapi-generator (python-fastapi) + pydantic v2 often struggles with:
  - `oneOf`/`anyOf` wrappers (producing wrapper classes that break JSON schema
    generation in FastAPI `/openapi.json`, or requiring awkward payload shapes)
  - very large integer bounds (e.g. Uint64 max) that can overflow signed-int64
    internal representations and yield invalid runtime constraints.

For code generation only, we simplify those patterns.

Transformations
---------------
1) oneOf handling:
   - if schema is pure polymorphic union (`oneOf` only): collapse to 1st branch
   - else: drop `oneOf` and keep other shape-defining keys

2) anyOf handling:
   - 3GPP forward-compatible enum pattern
       anyOf: [ {type:string, enum:[...]}, {type:string} ]
     => plain `{type: string}` (keep description)

3) integer bounds:
   - drop `maximum` if > 2^63-1
   - drop `minimum` if < -2^63

Usage
-----
  python tools/build_simplified_specs.py

Output
------
  simplified/<same-filename-as-original>.yaml
  (e.g. simplified/TS29564_Nupf_EventExposure_PoC_ETRI_DoDo1.yaml)
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml


REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = REPO_ROOT / "simplified"

DOMAIN_YAMLS = (
    "Nncof_EventsSubscription_PoC_ETRI_DoDo1.yaml",
    "TS29508_Nsmf_EventExposure_PoC_ETRI_DoDo1.yaml",
    "TS29564_Nupf_EventExposure_PoC_ETRI_DoDo1.yaml",
    "TS29591_Nnef_EventExposure_PoC_ETRI_DoDo1.yaml",
    "TS29571_CommonData_PoC_ETRI_DoDo1.yaml",
    "TS29122_CommonData_PoC_ETRI_DoDo1.yaml",
    "TS26510_CommonData_PoC_ETRI_DoDo1.yaml",
    "TS26512_CommonData_PoC_ETRI_DoDo1.yaml",
    "SupplementaryData_PoC_ETRI_DoDo1.yaml",
)

GENERATED_HEADER = (
    "# !!! GENERATED FILE - DO NOT EDIT MANUALLY !!!\n"
    "# Generated by tools/build_simplified_specs.py from original specs.\n"
    "# Edit original YAMLs in repo root, then re-run:\n"
    "#     python tools/build_simplified_specs.py\n"
)

_SCHEMA_SHAPE_KEYS = ("type", "properties", "$ref", "allOf", "items", "enum")
_INT64_MAX = 2**63 - 1
_INT64_MIN = -(2**63)


def _is_forward_compat_enum(node: dict) -> bool:
    items = node.get("anyOf")
    if not isinstance(items, list) or len(items) != 2:
        return False
    a, b = items
    return (
        isinstance(a, dict)
        and isinstance(b, dict)
        and a.get("type") == "string"
        and isinstance(a.get("enum"), list)
        and b.get("type") == "string"
        and "enum" not in b
    )


def _drop_overlarge_int_bounds(node: dict) -> dict:
    if node.get("type") != "integer":
        return node
    if "maximum" in node and node["maximum"] > _INT64_MAX:
        node = {k: v for k, v in node.items() if k != "maximum"}
    if "minimum" in node and node["minimum"] < _INT64_MIN:
        node = {k: v for k, v in node.items() if k != "minimum"}
    return node


def simplify(node: Any) -> Any:
    if isinstance(node, dict):
        if "oneOf" in node and not any(k in node for k in _SCHEMA_SHAPE_KEYS):
            branches = node["oneOf"]
            if isinstance(branches, list) and branches:
                return simplify(branches[0])

        if "oneOf" in node:
            node = {k: v for k, v in node.items() if k != "oneOf"}

        if _is_forward_compat_enum(node):
            out = {"type": "string"}
            if "description" in node:
                out["description"] = node["description"]
            return out

        node = _drop_overlarge_int_bounds(node)
        return {k: simplify(v) for k, v in node.items()}

    if isinstance(node, list):
        return [simplify(x) for x in node]

    return node


class _BlockStringDumper(yaml.SafeDumper):
    pass


def _str_presenter(dumper: yaml.SafeDumper, data: str):
    if "\n" in data:
        return dumper.represent_scalar("tag:yaml.org,2002:str", data, style="|")
    return dumper.represent_scalar("tag:yaml.org,2002:str", data)


_BlockStringDumper.add_representer(str, _str_presenter)


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for name in DOMAIN_YAMLS:
        src = REPO_ROOT / name
        dst = OUT_DIR / name
        with src.open() as f:
            doc = yaml.safe_load(f)
        doc = simplify(doc)
        body = yaml.dump(
            doc,
            Dumper=_BlockStringDumper,
            sort_keys=False,
            allow_unicode=True,
            width=120,
        )
        dst.write_text(GENERATED_HEADER + body)
        print(f"  -> {dst.relative_to(REPO_ROOT)} ({dst.stat().st_size:,} bytes)")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())

